# Generated by Django 3.2.13 on 2022-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=350, null=True, verbose_name='Nome: ')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade: ')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo: ')),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
    ]
